{easy
	{balancingFactorBonus {cp 0.25} {mp 30.00} {payback 1.00} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{normal
	{balancingFactorBonus {cp 0.30} {mp 30.00} {payback 2.00} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{hard
	{balancingFactorBonus {cp 0.40} {mp 30.00} {payback 4.00} }
	{chargeFactors
		{value "*=1.0"}
	}
}
{heroic
	{balancingFactorBonus {cp 0.50} {mp 30.00} {payback 8.00} }
	{chargeFactors
		{value "*=1.0"}
	}
}